import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import ClientLayout from "@/components/ClientLayout";
import PageTransition from "@/components/PageTransition";
import Navbar from "@/components/sections/ui/common/navbar";
import Footer from "@/components/sections/ui/common/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Personal Portfolio",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: "/me/logo.png", type: "image/png" },
      { url: "/me/logo-24.png", sizes: "24x24" },
    ],
    apple: "/me/logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <ClientLayout />
        <PageTransition>{children}</PageTransition>
        <Footer />
      </body>
    </html>
  );
}
